name:                HaskellEsqueleto
version:             0.1.0.0
github:              "githubuser/HaskellEsqueleto"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskellEsqueleto#readme>

dependencies:
- base
- text
- hex-text
- casing
- time
- timeit
- bytestring
- containers
- unordered-containers
- vector
- transformers
- mtl >= 2.2.2
- multimap
- direct-sqlite
- persistent
- persistent-sqlite
- persistent-template
- esqueleto >= 3.4.0.0
- aeson
- aeson-casing
- base64-bytestring
- system-fileio
- system-filepath

library:
  source-dirs: src
  ghc-options:
    - -Wno-partial-type-signatures

executables:
  HaskellEsqueleto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-partial-type-signatures
    dependencies:
    - HaskellEsqueleto

tests:
  HaskellEsqueleto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellEsqueleto
